services:
  db:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=sagar
      - POSTGRES_PASSWORD=sagar
      - POSTGRES_DB=ny_taxi
    ports:
      - '5433:5432'
    volumes:
      - "/Users/sagarbhavsar/MyRepo/de_camp/module_1/2_docker_postgres/ny_taxi_postgres_data:/var/lib/postgresql/data"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80" 
